### ISSUE TITLE
Blog Section 

### ISSUE THREAD

**Issue by skyfaerie** [GothamSass/chrysler#54]
Blog section will contain all blog posts 

### Main Blog Page
* Blog title
* Blog description 
* Blog roll
  * Post title connecting to full blog post
  * Post date and author
  * Post teaser (description)

### Blog Post 
Each blog post will contain: 
* Blog title
* Blog date and author 
* Blog content 
* Link to previous and next blog

#25 

### Subtasks

- [x] Add [microformats classes](http://microformats.org/wiki/h-entry) to blog teaser and node page markup. we may not use all of them. also don't need to worry about backwards compatibility.
- [x] Update author code to handle multiple authors (both json and markup).
- [x] Add tags (to json and markup)
- [x] Add _About this Author_ footer to blog node page.
- [x] @rmjames Add moment.js library for date formatting
- [x] @nonlinear user interface structure

**Comment by skyfaerie** [comment]
This is complete. See PR #53

**Comment by misscs** [comment]
Added subtasks based on recent comments on PR #53. 

@rmjames Added a task for you to add moment.js for date formatting.

@nonlinear Added basic structure task for you.

**Comment by skyfaerie** [comment]
Blog teaser is now pulling json correctly. Still need to get data on the blog page itself and figure out the multiple authors thing.

**Comment by skyfaerie** [comment]
Moving user interface and moment.js tasks  into separate issues. The rest of the blog stuff is done .

**Comment by misscs** [comment]
This is d-o-n-e. @skyfaerie is double checking that her local compile issues are resolved and then she'll merge in the PR.
